### ISSUE TITLE
Doubleshot bonuses are missing items?

### ISSUE THREAD

**Issue by Question2** [Pfhoenix/DDONamedGearPlanner#15]
![image](https://user-images.githubusercontent.com/1191378/155058006-900ebb87-57b5-48de-b122-cfcd93dfdfdf.png)

It says there are 9 items with an enhancement bonus, but its only displaying cannith crafting trinkets. Insight bonuses say there are 4 items, but display none.

**Comment by Pfhoenix** [comment]
You posted a screenshot of someone else's tool, the web-based one.
