### ISSUE TITLE
discrepancy with movement speed values on gear

### ISSUE THREAD

**Issue by markusdf** [Pfhoenix/DDONamedGearPlanner#2]
compare "quicksilver cassok" Move speed enhancement: 25
and
skirmisher's belt Move speed enhancement: 8

the cassock is using speed increase notation of 25%, whereas the belt is using hte notation Speed XIII, which actually means move speed 30%

similar issue with melee/ranged attack speed on items with the same notation as the belt.

**Comment by Pfhoenix** [comment]
Fixed in the next update.
